services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  web:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend/todo-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/todo-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - web

volumes:
  mongodata: